### ISSUE TITLE
Deployment failing on 9.2 branch to local docker

### ISSUE THREAD

**Issue by phaniav** [Sitecore/Sitecore.Demo.Platform#168]
Hi,
When I am running build.ps1 with "Docker_Unicorn" target, I am facing the below error during transformation. I tried manually publishing the missing web.config file, but, couldn't resolve the issue. 

```
========================================
Apply-DotnetCore-Transforms
========================================
Executing task: Apply-DotnetCore-Transforms
Warning: The alias GetFiles has been made obsolete. Please use the GetFiles overload that accept globber settings instead.
Skipping c:/Deploy/transforms/web.azure.config.project.website.xdt
Skipping c:/Deploy/transforms/web.azure.config.xdt
Applying configuration transform:c:/Deploy/transforms/web.config.project.website.appsettings.xdt
An error occurred when executing task 'Apply-DotnetCore-Transforms'.
Error: System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not find file 'C:\Project\Sitecore.HabitatHome.Platform\Publish\Web\web.config'.
```
Also, looking into the build.cake file, for DotNetCore, destination should be `publish\xConnect` or `publish\web`?

```
Task("Apply-DotnetCore-Transforms").Does(() => {
  var publishFolder = $"{configuration.PublishTempFolder}";
  var destination = configuration.WebsiteRoot;
  if (publishLocal) {
    destination = configuration.PublishWebFolder;
  }
  string[] excludePattern = {"ssl","azure"};
  Transform(publishFolder, "transforms", destination, excludePattern);
});
```

My cake-config.json looks like below

```
{
	"WebsiteRoot": "C:\\Inetpub\\wwwroot\\habitathome.dev.local",
	"XConnectRoot": "C:\\Inetpub\\wwwroot\\habitathome_xconnect.dev.local\\",
	"InstanceUrl": "https://habitathome.dev.local",
	"SolutionName": "HabitatHome.sln",
	"ProjectFolder": "C:\\Project\\Sitecore.HabitatHome.Platform",
	"UnicornSerializationFolder": "C:\\Project\\Sitecore.HabitatHome.Platform\\items",
	"BuildConfiguration": "Debug",
	"BuildToolVersions": "VS2017",
	"RunCleanBuilds": false,
	"MessageStatisticsApiKey": "XXXXXXXXXXXXXXXXX",
	"MarketingDefinitionsApiKey": "XXXXXXXXXXXXXX",
	"DeployExmTimeout": 60,
	"PublishTempFolder": "c:\\Deploy",
	"version": "9.2.0",
	"CDN": "false",
	"SitecoreAzureToolkitPath": "C:\\Users\\name\\Downloads\\Sitecore\\sat230"
}
```
and my .env file is
```
WINDOWSSERVERCORE_CHANNEL=1903
NANOSERVER_CHANNEL=1903
REGISTRY=
REMOTEDEBUGGER_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Remote Debugger
```

**Comment by jeanfrancoislarente** [comment]
Thanks for the feedback / report @phaniav.

I'm just finishing up some fixes and should have those out next week.

**Comment by phaniav** [comment]
@jeanfrancoislarente were you able to fix the above issue? Please let me know if there is a branch I can use in the meanwhile. Thanks in advance.

Phani.

**Comment by jeanfrancoislarente** [comment]
We're still in a big refactor fix... Should be very soon. Thanks for your patience @phaniav

**Comment by jeanfrancoislarente** [comment]
Hey @phaniav - I didn't ignore you on purpose but as you know we try to move forward all the time and generally only focus on the latest version of Sitecore. 

As such we don't have time to spend investigating prior branches or issues. I'm going to close this issue since we won't be working on it.

We have recently updated the repo to work with the latest Sitecore version 10.0.0 which includes images publicly available on Sitecore's official container registry (scr.sitecore.com).

Please feel free to try out the latest version!
