### ISSUE TITLE
We are getting Referrer as google but not the keyword ? Why

### ISSUE THREAD

**Issue by manigmailgithub** [Sitecore/Sitecore.Demo.Platform#182]
Hi Team,

When we are doing the organic search of the site. The Referrer is shown as google but the keyword is not captured. 
Can you please help on what is this gap and how to overcome on this. 

Regards,
Mani Athmanathan

**Comment by harshbaid** [comment]
I think this is limitation on google's side since they don't pass the keyword over in recent changes in google search.

**Comment by scottmulligan** [comment]
Thanks @harshbaid. You are correct.

This is not an issue specific to the demo or the Sitecore product as Google no longer passes keyword info. We will send a feature request to the product team to have this functionality kemoved.
