### ISSUE TITLE
Error: the following paths have collided (e.g. case-sensitive paths on a case-insensitive filesystem) and only one from the same colliding group is in the working tree

### ISSUE THREAD

**Issue by MartinMiles** [Sitecore/Sitecore.Demo.Platform#188]
After cloning from github got he following message:

"the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree" 

Affected items:

  'items/Project/Global/Content/Demo SXA Sites/Global/Presentation/Partial Designs/Shared/Guides/Article Content.yml'
  'items/project/Global/Content/Demo SXA Sites/Global/Presentation/Partial Designs/Shared/Guides/Article Content.yml'
  'items/Project/Global/Content/Demo SXA Sites/Global/Presentation/Partial Designs/Shared/Guides/Article Extra.yml'
  'items/project/Global/Content/Demo SXA Sites/Global/Presentation/Partial Designs/Shared/Guides/Article Extra.yml'
  'items/Project/Global/Content/Demo SXA Sites/Global/Presentation/Partial Designs/Shared/Guides/Article List.yml'
  'items/project/Global/Content/Demo SXA Sites/Global/Presentation/Partial Designs/Shared/Guides/Article List.yml'
  'items/Project/Global/Content/Demo SXA Sites/Global/Presentation/Rendering Variants/Link List/Social Links.yml'
  'items/project/Global/Content/Demo SXA Sites/Global/Presentation/Rendering Variants/Link List/Social Links.yml'
  'items/Project/Global/Content/Demo SXA Sites/Global/Presentation/Rendering Variants/Link List/Social Links/Link.yml'
  'items/project/Global/Content/Demo SXA Sites/Global/Presentation/Rendering Variants/Link List/Social Links/Link.yml'

**Comment by jeanfrancoislarente** [comment]
Thanks @MartinMiles!

This issue was fixed internally a couple of weeks ago, I just pushed main branch out to GitHub now which should resolve the issue.
