### ISSUE TITLE
Manifest unknown error while pulling the image

### ISSUE THREAD

**Issue by jitendrasoni** [Sitecore/Sitecore.Demo.Platform#189]
Today, I was trying to pull the latest image using  docker-compose pull  for the new lighthouse instance setup, I found a few errors
ERROR: for tenant service  manifest for scr.sitecore.com/demo/base/lighthouse-xp0-modules-tenant-service:10.0-ltsc2019-1001.0 not found: manifest unknown: manifest tagged by "10.0-ltsc2019-1001.0" is not found
do we need to explicitly pass the image tag, any suggestion?

I think the issue is because of the latest change in the .env file and the relative tags are missing in the image repository.

Slack reference -  https://sitecorechat.slack.com/archives/C5VQ5SVKJ/p1609713872396800

**Comment by scottmulligan** [comment]
Can you please try again with the latest main branch? We no longer see this issue after the recent updates. Thanks for the feedback!

**Comment by jitendrasoni** [comment]
Thanks @scottmulligan  It's working!
