### ISSUE TITLE
Typo in docker/build-and-push-images.yml

### ISSUE THREAD

**Issue by SinghSarabpreet05** [Sitecore/Sitecore.Demo.Platform#190]
At line 213:

SQL_SA_PASSWORD=$(SQL_SA_PASSWORD}

The bracket is closed incorrectly

**Comment by jeanfrancoislarente** [comment]
Hey @SinghSarabpreet05,

Thanks for catching this!

Did you notice any build failures, issues or just noticed the typo? 

(Trying to evaluate urgency)

**Comment by SinghSarabpreet05** [comment]
Hey @jeanfrancoislarente 

I just noticed the typo. For me, it's not very urgent as I have cloned it in my Azure repo and working from there only.

I also noticed that the typo repeats for all the SQL_SA_PASSWORD=$(SQL_SA_PASSWORD} in the same file.

**Comment by jeanfrancoislarente** [comment]
Great, thanks!

Copy & paste, clearly. We'll fix it up internally and it will eventually make its way here, thanks again!
