### ISSUE TITLE
cm server unhealthy - exception in log

### ISSUE THREAD

**Issue by dmead35** [Sitecore/Sitecore.Demo.Platform#192]
Steps:
1. docker-compose up -d
--using the latest images.  I did not build my own images.
Expected result:
Works
Actual result:
all other servers come up fine except cm server which never comes up healthy yet.  

Details below.

1. Here is the unhealthy error during docker-compose up

C:\Projects\Sitecore.Demo.Platform>docker-compose up -d
Creating sitecore-xp0_smtp_1  ... done
Creating sitecore-xp0_mssql_1 ... done
Creating sitecore-xp0_solr_1  ... done
Creating sitecore-xp0_id_1       ... done
Creating sitecore-xp0_ps_1       ... done
Creating sitecore-xp0_xconnect_1 ... done
Creating sitecore-xp0_authoringhost_1 ... done
Creating sitecore-xp0_xdbautomationworker_1 ... done
Creating sitecore-xp0_xdbsearchworker_1     ... done
Creating sitecore-xp0_cm_1                  ... done
Creating sitecore-xp0_cd_1                  ... done

ERROR: for init  Container "3b771d9b9bb7" is unhealthy.

ERROR: for traefik  Container "3b771d9b9bb7" is unhealthy.
ERROR: Encountered errors while bringing up the project.

2. here is the output showing the unhealthy cm server from docker ps command:

3b771d9b9bb7   scr.sitecore.com/demo/lighthouse-xp0-cm:10.0.1-ltsc2019-1001.0                    "powershell.exe -Com…"     3 minutes ago   Up 3 minutes (unhealthy)   80/tcp                                         sitecore-xp0_cm_1

All other ones are healthy according to Docker

3. I see these errors in the docker-compose logs -f - coming from the CM server:

 3016 18:28:14 ERROR Could not resolve type name: Sitecore.Demo.Feature.Platform.CRM.ExperienceProfile.ExperienceProfileSalesforceInitializeRoutes, Sitecore.Demo.Feature.Platform.CRM (method: Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).

There may be others.

Please fix?

**Comment by dmead35** [comment]
I did a CLI to the cm container, and using CLI on the cm container I deleted *CRM* from wwwroot\bin and Feature\CRM under C:\items and the CRM config files under App_Config\Include.  Then iisreset.  After that, the CM server worked.

**Comment by dmead35** [comment]
When I tried to use these images for a high pressure demo, this was the main blocker, that I had to resolve myself per steps described above, after deploying the container.  Then it worked.

**Comment by scottmulligan** [comment]
Thanks! We have found the cause of the issue.

We will have a small change out today and will update this thread.

**Comment by jeanfrancoislarente** [comment]
Spoiler alert @dmead35 - The fix will be to update the .env value for `DEMO_VERSION` to `1001.1` instead of `1001.0`.

We're just validating at the moment, but ... it makes sense.

**Comment by scottmulligan** [comment]
Thanks again for reporting @dmead35. Updated and tested with the version bump.

**Comment by quachnguyen** [comment]
Sorry for re-open this issue, I'm using the latest version of this repository and DEMO_VERSION=1010.0 But the error is still persist, do I need to downgrade to the old **(1001.1)** version?  

![image](https://user-images.githubusercontent.com/128512/139889616-24ac8586-2f22-40bf-b184-f9821d93fb6f.png)

Could you recheck it?
