### ISSUE TITLE
error running build-images.ps1

### ISSUE THREAD

**Issue by dmead35** [Sitecore/Sitecore.Demo.Platform#193]
First time attempting to build my own images.  I don't want to build my own images but I need lighthouse to work so I am trying to be able to modify the images in case I need to fix something.

David

Steps:
1. C:\Projects\Sitecore.Demo.Platform> .\build-images.ps1 -Memory 8G
 (per instructions in Usage.md)

Expected result:
Works

Actual result:
Error response from daemon: manifest for scr.sitecore.com/demo/base/lighthouse-xp1-modules-base-cd:10.0.1-ltsc2019-1001.1 not found: manifest unknown: manifest tagged by "10.0.1-ltsc2019-1001.1" is not found

Details:

PS C:\Projects\Sitecore.Demo.Platform> .\build-images.ps1 -Memory 8G
Pulling base images...
WARNING: The INTERNAL_NUGET_SOURCE variable is not set. Defaulting to a blank string.
WARNING: The SYSTEM_ACCESSTOKEN variable is not set. Defaulting to a blank string.
10.0.1-ltsc2019: Pulling from community/sitecore-custom-horizon-authoringhost
21be49aa856f: Already exists
7433538cdf5f: Already exists
9ff5e15d3fc0: Already exists
2f31fcd035e2: Already exists
d4a5d1fefb3c: Already exists
95067ae670a3: Already exists
b6ca5241f4bb: Pull complete
9b9bff1f5e99: Pull complete
1569a0eb5a33: Pull complete
3462c1c34248: Pull complete
a3363f86ea57: Pull complete
4b0ab15154a6: Pull complete
b994b1ae52ea: Pull complete
Digest: sha256:6a2e20ca9aed4943979cc00309d13733e3525e69090f05b0d6bd5467ab9d81fe
Status: Downloaded newer image for scr.sitecore.com/community/sitecore-custom-horizon-authoringhost:10.0.1-ltsc2019
scr.sitecore.com/community/sitecore-custom-horizon-authoringhost:10.0.1-ltsc2019
External image 'scr.sitecore.com/community/sitecore-custom-horizon-authoringhost:10.0.1-ltsc2019' is latest.
Error response from daemon: manifest for scr.sitecore.com/demo/base/lighthouse-xp1-modules-base-cd:10.0.1-ltsc2019-1001.1 not found: manifest unknown: manifest tagged by "10.0.1-ltsc2019-1001.1" is not found
Failed.
At C:\Projects\Sitecore.Demo.Platform\pull-build-images.ps1:17 char:64
+ ... CODE -ne 0 | Where-Object { $_ } | ForEach-Object { throw "Failed." }
+                                                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed.

PS C:\Projects\Sitecore.Demo.Platform>

**Comment by dmead35** [comment]
Is this user error on my part?  Anyone else also seeing this?

**Comment by jeanfrancoislarente** [comment]
Have you tried more recently @dmead35 ?
There was an issue with getting the base images out to scr.sitecore.com which _should_ be resolved now. 

The image referenced in your error above is [now in the ACR](https://github.com/Sitecore/docker-images/blob/master/tags/sitecore-tags.md#lighthouse-xp1-modules-base-cd)

Please re-open if this is still an issue.

**Comment by dmead35** [comment]
I haven't tried lately - but sounds good, glad it's there now.  thx
