### ISSUE TITLE
Cannot build the solution due to missing Coveo dlls

### ISSUE THREAD

**Issue by reyrahadian** [Sitecore/Sitecore.Demo.Platform#195]
Right after I get the latest code I cannot build the solution successfully because Sitecore.Demo.Platform.Foundation.CoveoIndexing contains reference error. Upon inspecting the reference it appears that all the Coveo dlls are missing from the project.

Are we expected to add this in manually? I was under the assumption that the Coveo integration is an optional feature after reading the documentation.

**Comment by scottmulligan** [comment]
The Coveo references are not available on Nuget at this time. As a workaround we added a powershell script that needs to be run.

.\pull-build-libraries.ps1

This script only needs to be run if building the solution locally, not if pulling and running in containers only.
