### ISSUE TITLE
CoveoIndexing Project dll missing

### ISSUE THREAD

**Issue by ArulPushpam** [Sitecore/Sitecore.Demo.Platform#196]
![image](https://user-images.githubusercontent.com/49192393/108401634-8e8dd580-7242-11eb-842c-883a08ea8a3a.png)
**Sitecore.Demo.Platform.Foundation.CoveoIndexing** - In csproj file, you have mentioned four dll in lib folder, since lib folder is empty, so I'm getting an error while building the project

Missed DLL:
Coveo.AbstractLayer
Coveo.Framework
Coveo.SerachProvider.Rest
Coveo.SearchProviderbase

**Comment by scottmulligan** [comment]
Hi there!

Copy of: https://github.com/Sitecore/Sitecore.Demo.Platform/issues/195

The Coveo references are not available on Nuget at this time. As a workaround we have a powershell script that needs to be run.

.\pull-build-libraries.ps1

This script only needs to be run if building the solution locally, not if pulling and running in containers only.
