### ISSUE TITLE
Modify.ContentHub-variable - source file not found -  .\build.ps1

### ISSUE THREAD

**Issue by ArulPushpam** [Sitecore/Sitecore.Demo.Platform#197]
![image](https://user-images.githubusercontent.com/49192393/108504130-6ef6bb80-72db-11eb-9cf2-105c2a6c1f49.png)
While run this comment in powershell, i got this isse
 .\build.ps1

**Comment by jeanfrancoislarente** [comment]
Please provide much more details... 

- What's the exact command you used?
- Did you read through docs/usage.md. Building has dependencies and you should understand the demo environment.
- Which branch are you on, when did you update last?
- What's your mother's maiden name (kidding, don't answer that one)
