### ISSUE TITLE
Docker compose pull - smtp image issue

### ISSUE THREAD

**Issue by epgeekhive** [Sitecore/Sitecore.Demo.Platform#198]
Hi,

When  "docker-compose pull" is executed, the smtp image throws an error. 

![image](https://user-images.githubusercontent.com/79541076/108905679-fe5ae200-75ed-11eb-8230-f905361024bb.png)

**Comment by jeanfrancoislarente** [comment]
ensure "experimental" mode is enabled on Docker.

**Comment by jeanfrancoislarente** [comment]
https://github.com/Sitecore/Sitecore.Demo.Platform/blob/main/docs/Usage.md#preparing-docker
