### ISSUE TITLE
Deploy Marketing Definitions Error

### ISSUE THREAD

**Issue by rollewp** [Sitecore/Sitecore.Demo.Platform#202]
- Navigate to the control panel
- Deploy marketing definitions
- Observe the error
ManagedPoolThread #2 15:41:35 INFO Job started: Deploy all definitions. Deployment job id: b230a916-a2e9-4be7-8af1-68efdb1ad677.
1396 15:41:35 ERROR Cannot finish Analytics page tracking
Exception: System.ArgumentNullException
Message: CurrentPage should not be null.
Parameter name: CurrentPage

**Comment by jflheureux** [comment]
Are you able to replicate this one on demand? My first guess is that error is unrelated to the "Deploy Marketing Definitions" but occurred just as you started that job.

**Comment by rollewp** [comment]
I did not think to try it twice! The second deploy worked.
