### ISSUE TITLE
Documentation error on Sitecore admin username

### ISSUE THREAD

**Issue by Vapok** [Sitecore/Sitecore.Demo.Platform#221]
Hello,

At some point along the way, it's apparent that the username to log into the CM of Sitecore for Lighthouse was changed from "admin" to "superuser".

In going through the doc today on this, I found that the documentation showed:
![image](https://user-images.githubusercontent.com/1264136/179256951-b415e809-ac89-4484-907a-00b75dc99ccd.png)

But it didn't work.. when looking through Docker variables, I see this:
![image](https://user-images.githubusercontent.com/1264136/179257077-b0358f86-420f-47bf-b00c-fab33c58e5ee.png)

Using "superuser" as noted in the Docker variables worked, but not Admin.

Just thought I'd let you all know.

**Comment by adoprog** [comment]
Thanks, this was fixed some time ago.
