### ISSUE TITLE
admin login doesn't work

### ISSUE THREAD

**Issue by zell71** [Sitecore/Sitecore.Demo.Platform#226]
I've noticed i was unable to login with superuser credentials as stated in the documentation.
reviewing the user credentials in SQL, this username doesn't exist.. I've tested admin/b but still no joy.
i even reset the credentials for admin (using a SQL update) but still unable to login.

**Comment by adoprog** [comment]
Are you running the project locally? Please check the mssql-init container logs. If resetting admin via SQL keep in mind that we use SHA256 password hashing in the project.

If there are errors related to SQL connection trust in mssql-init - we're working on a fix currently, basically all Invoke-SqlCmd commands in the project need "-TrustServerCertificate" after the recent update from Microsoft.

**Comment by sanjeev-choudhuri** [comment]
Hi Team,

Attached the log for Container name: 'sitecore-xp0-mssql-init-1' getting stopped and having error in logs. Please find the attached.
[logs.txt](https://github.com/Sitecore/Sitecore.Demo.Platform/files/11561262/logs.txt)

Even on verify the username and password we could not bale to login. What steps to perform to login through the sitecore.

Regards,
Sanjeev Choudhuri

**Comment by jflheureux** [comment]
As Alexander said earlier, if there are errors related to SQL connection trust in mssql-init - we're working on a fix currently, basically all Invoke-SqlCmd commands in the project need "-TrustServerCertificate" after the recent update from Microsoft.

By looking at your log file, this is exactly what is happening. You can fix it by yourself by:
1. Open the solution folder in vs code.
2. Search for all occurrences of "Invoke-Sqlcmd".
3. Add a "-TrustServerCertificate" parameter to all of these commands.
4. Stop your containers running the "down.ps1" script.
5. Clean your container data by running the "CleanDockerData.ps1" script.
6. Recreate your containers by running the "Up.ps1" script.

**Comment by sanjeev-choudhuri** [comment]
Hi Jeff,

Thanks again for update on this issue, it worked quite well. And able to login to CM now.

Regards,
Sanjeev Choudhuri
