### ISSUE TITLE
mssql-int error

### ISSUE THREAD

**Issue by vemanavk** [Sitecore/Sitecore.Demo.Platform#227]
![image](https://github.com/Sitecore/Sitecore.Demo.Platform/assets/67726423/6bfb5d51-5511-4cdd-83a1-65b5e52e9a00)

**Comment by jflheureux** [comment]
Per your screenshot, this error have nothing to do with the mssql-init image/container.
This is a generic Docker error.
Please validate that your environment is correctly setup to build and run Sitecore containers by running this script: https://github.com/strezag/sitecore-containers-prerequisites

**Comment by vemanavk** [comment]
> 

![image](https://github.com/Sitecore/Sitecore.Demo.Platform/assets/67726423/fdcfcf72-8c4a-4ae1-a119-919811acf3a6)
