### ISSUE TITLE
Getting error due to timeout.

### ISSUE THREAD

**Issue by sanjeev-choudhuri** [Sitecore/Sitecore.Demo.Platform#228]
Hi Team,

I am getting error at 28th step while copy from : Step 28/42 : COPY --from=cmp_assets /module/cm/content /inetpub/wwwroot.
<img width="948" alt="up" src="https://github.com/Sitecore/Sitecore.Demo.Platform/assets/29660241/53a99349-45fb-4868-89f3-d397d3547ad1">

**Comment by jflheureux** [comment]
Have you tried to retry the PowerShell command? Sometimes container image builds are failing for all sorts of random reasons. Retrying often fixes the issue.

**Comment by sanjeev-choudhuri** [comment]
Good Day!,

Yes, seems container image builds failing and tried multiple times to execute. Is there any way to start up the containers from specific images failing. As even if I tried to rerun then it's taking more space in docker with some None defined images or other.
**One every run I use to clean and start from initial to avoid consuming more space.**

Please suggest on this.

Regards,
![Timeout issue](https://github.com/Sitecore/Sitecore.Demo.Platform/assets/29660241/e7c521b8-b627-4e97-b1f2-c49cdba4b1b2)
![Docker](https://github.com/Sitecore/Sitecore.Demo.Platform/assets/29660241/6a020157-ccc3-4261-9ece-c92193de8060)

**Comment by sanjeev-choudhuri** [comment]
Hi Jeff,

Lastly on multiple iteration there is issue with Manisfest while connecting remote.
![ManisfestIssue](https://github.com/Sitecore/Sitecore.Demo.Platform/assets/29660241/50c9955c-388a-4ee7-b979-76a8ed2c423f)

Also, this time the images grown from 35 to 44 in docker. As I re-run from previous breaking point.
![DockerImage](https://github.com/Sitecore/Sitecore.Demo.Platform/assets/29660241/115eee7e-9763-4097-bcdc-779dda2c223a)


Regards,
Sanjeev Choudhuri

**Comment by jflheureux** [comment]
Thanks for the screenshots. From them, I can see 2 things that are preventing you from success:
1. You are running Docker Desktop v4.19.0.
   1. This version of Docker Desktop is no longer able to run Windows and Linux containers in parallel from the same compose file (LCOW). v4.18.0 was the last version to be able to do so. You must downgrade Docker Desktop to v4.18.0 or lower.
3. You are running Docker Desktop with "Docker Compose V2" enabled.
   1. At the time this repository was last maintained, "Docker Compose V2" was not the default configuration in Docker Desktop. This solution is not yet compatible with Docker Compose V2. You must disable that option in Docker Compose before building and starting the containers.

After making these changes, you might have other issues.

**Comment by sanjeev-choudhuri** [comment]
Thanks Jeff,

It helps, it's all set and up and running. Thanks for your notes and valuable time.

Regards,
Sanjeev Choudhuri
