### ISSUE TITLE
solr-init_1 could'nt able to restart.

### ISSUE THREAD

**Issue by sanjeev-choudhuri** [Sitecore/Sitecore.Demo.Platform#229]
Hi Team,

I could see after CM containers up the Solr container getting down. On checking of logs I could see its looking for different collection name.
**Sitecore collections are already exist. Use collection name prefix different from 'sitecore'.**

Even on I clear the entire containers and try to up with different name say, 'Sitecore102'. 
Even after that once containers are up solr containers getting down. Could not able to index.
 _**Sitecore collections are already exist. Use collection name prefix different from 'sitecore102'.**_

Logs Attached:
[SolrContainerLog.txt](https://github.com/Sitecore/Sitecore.Demo.Platform/files/11581516/SolrContainerLog.txt)

Regards,
Sanjeev Choudhuri

**Comment by jflheureux** [comment]
It is normal that the `solr-init` and `mssql-init` (not there in all demos) and `init` containers are exiting after their job is done. And it is normal they show logs similar to what you posted above on their second run. They are meant to initialize the environment on its first run. Maybe your first run was not successful and now you are stuck in a semi-initialized state.

1. Revert the `SOLR_CORE_PREFIX_NAME` environment variable to its original value `sitecore`
2. down.ps1
3. cleanDockerData.ps1 to remove all the solr data in the mapped volume.
4. up.ps1 to start from scratch.

**Comment by jflheureux** [comment]
Closed due to inactivity.
