### ISSUE TITLE
unable to load the service index for source https://sitecore.myget.org nor https://slpartners.myget.org

### ISSUE THREAD

**Issue by fbrinke1** [Sitecore/Sitecore.Demo.Platform#230]
I keep getting these errors and it appears that Sitecore has transitioned from myget to nuget.  Can someone update this repository to point to the appropriate nuget respository?

**Comment by adoprog** [comment]
MyGet is temporarily down (https://status.myget.org/), you can try to replace the feed URL by using the following guide:
https://support.sitecore.com/kb?id=kb_article_view&sysparm_article=KB1002999
