### ISSUE TITLE
Sitecore Content Serialization Feature is Absent

### ISSUE THREAD

**Issue by vsedletskyiEPAM** [Sitecore/Sitecore.Demo.Platform#232]
Hi,

As far I can see, solution contains `sitecore.json` file which remaining about new Sitecore serialization model (SCS).
Unfortunately, I can see `Unicorn` serialization config files, only, rather than `json` modules under each projects which configurate serialized items.

**Comment by adoprog** [comment]
@vsedletskyiEPAM Better later than never 😊. Sitecore Content Serialization was added in the latest release.

**Comment by vsedletskyiEPAM** [comment]
For sure 😁 thanks a lot
